<!-- FOOTER START-->
<div id="footer" class="clearfix">
<div class="inner clearfix">
<ul>
<li><a href="../sitemap/index.html"><img src="../images/footer_btn01.jpg" alt="サイトマップ" width="75" height="17" class="rollover" /></a></li>
<li><a href="../policy/policy.html"><img src="../images/footer_btn02.jpg" alt="プライバシーポリシー" width="114" height="17" class="rollover" /></a></li>
<li class="pagetop"><a href="#container"><img src="../images/page_top.jpg" alt="ページトップへ戻る" width="141" height="23" class="rollover" /></a></li>
</ul>
<div class="clearfix">
<address><img src="../images/footer_address.jpg" alt="山田為商店　大阪府 大阪市浪速区 恵美須東1丁目22-16" width="283" height="13" /></address>
<p id="copyright"><img src="../images/footer_copyright.jpg" alt="(C)Yamada Tame Shoten Ltd. All Right Reserved" width="283" height="13" /></p>
</div>
</div>
</div>
<!-- FOOTER END -->
