<!-- HEADER START -->
<div id="header">
<div class="inner clearfix">
<div>
<p id="logo"><img src="../images/top/header_title.jpg" alt="山田為商店" width="646" height="72" /></p>
<div id="courtesy-navi" class="clearfix">
<p><img src="../images/top/header_seach.jpg" alt="サイト内検索" width="74" height="72" /></p>
<form action="http://www.yamatame.com/search.html" id="cse-search-box">
<input type="hidden" name="cx" value="014216636439543729317:yyuth2h9xyu" />
<input type="hidden" name="cof" value="FORID:9" />
<input type="hidden" name="ie" value="UTF-8" />
<span>
<input type="text" name="q" />
</span>
<input type="image" id="btn" class="rollover" src="../images/top/header_seach_btn.jpg" alt="検索" name="sa" value="検索" />
</form>
</div>
</div>
</div>
</div>
<!-- HEADER END -->
