<!-- SUB START -->
<div id="sub">
<h2><img src="/images/sub_sutitle.gif" alt="製品情報" width="214" height="39" /></h2>
<div class="category_list">
<h3><a href="/product_wire/index.html"><img src="/images/sub_btn01.jpg" alt="電線" width="214" height="54" /></a></h3>
<ul class="category">
<li><a href="/product_wire/magnet.html">マグネットワイヤー(焼付線)</a></li>
<li><a href="/product_wire/rectangular.html">平角線・丸線</a></li>
<li><a href="/product_wire/cca_wire.html">銅クラッドアルミ線(CCA Wire)</a></li>
<li><a href="/product_wire/stranded.html">撚り線</a></li>
<li><a href="/product_wire/triple-layer.html">三層絶縁電線</a></li>
<li class="end"><a href="/product_wire/insulation.html">絶縁電線・その他</a></li>
</ul>
</div>
<div class="category_list">
<h3><a href="/product_insulation/index.html"><img src="/images/sub_product_btn02.jpg" alt="絶縁材料" width="214" height="61" /></a></h3>
<ul class="category">
<li><a href="/product_insulation/tape.html">テープ</a></li>
<li><a href="/product_insulation/tube.html">チューブ</a></li>
<li class="twoline"><a href="/product_insulation/handa.html">半田・圧着端子・コネクター・非鉄金属・その他</a></li>
<li><a href="/product_insulation/insulationfilm.html">絶縁紙・絶縁布・絶縁フィルム</a></li>
<li class="end"><a href="/product_insulation/plastics.html">積層板・合成樹脂</a></li>
</ul>
</div>
<div class="category_list">
<h3><a href="/product_processed/index.html"><img src="/images/sub_product_btn03.jpg" alt="加工品" width="214" height="60" /></a></h3>
<ul class="category">
<li><a href="/product_processed/detail.html#title01">切削加工</a></li>
<li><a href="/product_processed/detail.html#title02">抜き加工・曲げ加工</a></li>
<li><a href="/product_processed/detail.html#title03">スリット加工</a></li>
<li><a href="/product_processed/detail.html#title04">金属加工</a></li>
<li><a href="/product_processed/detail.html#title05">ハーネス加工</a></li>
<li class="end"><a href="/product_processed/index.html#title06">その他</a></li>
</ul>
</div>

<div id="contact">
<h2><a href="https://www.yamatame.com/system/inquiries/" target="_blank"><img src="/images/sub_product_btn04.jpg" alt="お問い合わせ" width="214" height="40" /></a></h2>
<address>〒556-0002<br />
大阪市浪速区恵美須東１丁目22番16号</address>
<address>TEL　（06）6641-7551<br />
FAX　（06）6641-7559</address>
</div>



</div>
<!-- SUB END -->